#!/bin/bash
MAX_NO=0
#set variable max no. to 0
echo -n "Enter Number between (1 to 9) : "
read MAX_NO
#read the variable input
if ! [ $MAX_NO -ge 1 -a $MAX_NO -le 9 ] ; then
	echo "I asked to enter number between 1 to 9, Please"
	exit 1
fi
#if the max number is not between 1 and 9 exit the shell script 
clear

for (( i=1; i<=MAX_NO; i++ ))
do
#when i equal to 1 and i less than or  equal to max_no increment i doing for loop each time
	for (( s=MAX_NO; s>=i; s-- ))
	do
		echo -n " "
	done
	#when s equal max_no and s greater than or equal to i decrement s & do for loop
	for (( j=1; j<=i; j++ ))
	do
		echo -n " *"
	done
	#when j equal 1 and j less than or equal to i increment j & do for loop
	echo ""
done
# Second stage opposite of frst stage printing dots
for (( i=MAX_NO; i>=1; i-- ))
do
	for (( s=i; s<=MAX_NO; s++ ))
	do
	 echo -n " "
	done
	for (( j=1; j<=i; j++ ))
	do
	 echo -n " ."
	done
	echo ""
done

echo -e "JOB DONE!"
#program done print job done
